### ISSUE TITLE
Fix Original Vehicle Related Bugs

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#3078]
From #2400.
- [ ] #2216 (chairlift restricted to only one car in station to station mode) Issue caused by station direction special case for chairlifts. Could be fixed
- [ ] #2131 (Multi-tracked separate coasters) Issue caused by the logic not checking for unconnected track loops. Likely impossible to fix without messing with existing track exploits.
- [x] #2081 (Infinite Loop Crash) Issue caused by the logic which advances to the next track piece. Possibly introduce a count to prevent the stack overflow.
- [ ] #1923 , #1868 (Arrive at station glitches) 
- [x] #1411 & #1122 (Giga Coaster cable lift hill with block stations) Issue caused by logic not understanding correct layout for block stations and lift hills in certain configurations. Could be fixed
- [ ] #1303 (Vertical tracked rides with only station act strange) 
- [x] #866 (Improve Boat pathfinding) Could cause issues with backwards compatibility.

**Comment by Gymnasiast** [comment]
For #2131, I'd suggest not blocking it, but displaying an error warning the player that unexpected things might happen. That should allow for track exploits.

**Comment by PFCKrutonium** [comment]
If I may ask, why would #866 Cause issues with backwards compatibility?

**Comment by duncanspumpkin** [comment]
@PFCKrutonium if we have to change what variables mean in the vehicle structure it would cause issues with the boat not knowing what to do.

**Comment by PFCKrutonium** [comment]
So what would happen in the original game if when the game was loaded the boats had no data telling them to do anything, a blank slate?

**Comment by IntelOrca** [comment]
@duncanspumpkin why would we need to change what the variables mean?

**Comment by duncanspumpkin** [comment]
I was mainly thinking of the peep ai which stores a bunch of locations. I'm not completely sure if the boat ai does that but if it did the locations would have to be valid or it might cause issues when loading a from vanilla.

**Comment by SijmenSchoon** [comment]
This might be worth looking at again due to the milestone for v0.0.5

**Comment by Krutonium** [comment]
I feel that with NSF merged, it may be time to look at these again.

**Comment by Gymnasiast** [comment]
As all of these issues are already in our bug tracker on their own, I think there isn’t much point in keeping this open.
