### ISSUE TITLE
Implement drawing functions

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#3365]
#### Transport rides
- [x] `MINIATURE_RAILWAY` ~~#4478~~ #4619
- [x] `MONORAIL` #3737 
- [x] `SUSPENDED_MONORAIL` #4569
- [x] `CHAIRLIFT` #3511
- [x] `LIFT`#3677

#### Roller Coasters
- [x] `SIDE_FRICTION_ROLLER_COASTER` #4569
- [x] `VIRGINIA_REEL` #3435 
- [x] `REVERSER_ROLLER_COASTER` #4569
- [x] `WOODEN_ROLLER_COASTER` #4544
- [x] `WOODEN_WILD_MOUSE` #4523
- [x] `WILD_MOUSE` #4530
- [x] `INVERTED_HAIRPIN_COASTER` #4569
- [x] `JUNIOR_ROLLER_COASTER` #3169 
- [x] `MINI_ROLLER_COASTER` #4569
- [x] `SPIRAL_ROLLER_COASTER` #4569
- [x] `MINE_TRAIN_COASTER` #4569
- [x] `LOOPING_ROLLER_COASTER` #4569
- [x] `STAND_UP_ROLLER_COASTER` #4569
- [x] `CORKSCREW_ROLLER_COASTER` #4569
- [x] `LIM_LAUNCHED_ROLLER_COASTER` #4569
- [x] `TWISTER_ROLLER_COASTER` #4569
- [x] `GIGA_COASTER` #4569
- [x] `SUSPENDED_SWINGING_COASTER` #4569
- [x] `COMPACT_INVERTED_COASTER` #4569
- [x] `INVERTED_ROLLER_COASTER` #4569
- [x] `INVERTED_IMPULSE_COASTER` #4569
- [x] `MINI_SUSPENDED_COASTER` #4569
- [x] `STEEPLECHASE` #4569
- [x] `BOBSLEIGH_COASTER` #4569
- [x] `MINE_RIDE` #4569
- [x] `HEARTLINE_TWISTER_COASTER` #4569
- [x] `LAY_DOWN_ROLLER_COASTER` #4569
- [x] `FLYING_ROLLER_COASTER` #4569
- [x] `MULTI_DIMENSION_ROLLER_COASTER` #4569
- [x] `REVERSE_FREEFALL_COASTER` #4447
- [x] `VERTICAL_DROP_ROLLER_COASTER` #4569 
- [x] `AIR_POWERED_VERTICAL_COASTER` #4515 

#### Gentle rides
- [x] `MONORAIL_CYCLES` #3705 
- [x] `CROOKED_HOUSE` #3280 
- [x] `HAUNTED_HOUSE` #3652
- [x] `FERRIS_WHEEL` #3657
- [x] `MAZE` #3170 
- [x] `MERRY_GO_ROUND` #3653
- [x] `MINI_GOLF` #3220 
- [x] `OBSERVATION_TOWER` #3412
- [x] `CAR_RIDE` #3721 
- [x] `MINI_HELICOPTERS` #3664 
- [x] `SPIRAL_SLIDE` #3165 
- [x] `DODGEMS` #3180 
- [x] `SPACE_RINGS` #3692 
- [x] `CIRCUS_SHOW` #3649
- [x] `GHOST_TRAIN` #3724 
- [x] `FLYING_SAUCERS` #3648

#### Thrill rides
- [x] `TWIST` #3694 
- [x] `MAGIC_CARPET` #3701
- [x] `LAUNCHED_FREEFALL` #3678
- [x] `PIRATE_SHIP` #3682
- [x] `GO_KARTS`
- [x] `SWINGING_INVERTER_SHIP` #3698
- [x] `MOTION_SIMULATOR` #3279 
- [x] `3D_CINEMA` #3651
- [x] `TOP_SPIN`
- [x] `ROTO_DROP`#3673 
- [x] `ENTERPRISE` #3680

#### Water rides
- [x] `DINGHY_SLIDE` #4496
- [x] `LOG_FLUME` #4487
- [x] `RIVER_RAPIDS` #3672
- [x] `SPLASH_BOATS` #4482
- [x] `SUBMARINE_RIDE` #3538
- [x] `BOAT_RIDE` #3684
- [x] `RIVER_RAFTS` #3706
- [x] `WATER_COASTER` #4459

#### Shops / stalls
- [x] `FOOD_STALL`, `1D`, `1F`, `22`, `DRINK_STALL`, `SHOP`, `INFORMATION_KIOSK`, `CASH_MACHINE`,  `50`,`52`,`53`, `54`
- [x] `TOILETS`, `FIRST_AID`

#### Unknown
- [ ] `55`, `59`

### Vehicles
- [x] `DEFAULT` #3548
- [x] `LAUNCHED_FREEFALL` #3418
- [x] `OBSERVATION_TOWER` #3412
- [x] `RIVER_RAPIDS` #3548
- [x] `MINI_GOLF_PLAYER` #3220 
- [x] `MINI_GOLF_BALL` #3220 
- [x] `REVERSER` #3548
- [x] `SPLASH_BOATS_OR_WATER_COASTER` #3548
- [x] `ROTO_DROP` #3363 
- [x] `VEHICLE_VISUAL_SPLASH1_EFFECT ` #3548
- [x] `VEHICLE_VISUAL_SPLASH2_EFFECT ` #3548
- [x] `VEHICLE_VISUAL_SPLASH3_EFFECT ` #3548
- [x] `VEHICLE_VISUAL_SPLASH4_EFFECT ` #3548
- [x] `VEHICLE_VISUAL_SPLASH5_EFFECT ` #3548
- [x] `VIRGINIA_REEL` #3435
- [x] `SUBMARINE` #3399

### Other
- [x] `viewport_vehicle_paint_setup`
- [x] `viewport_peep_paint_setup` #3471
- [x] `viewport_misc_paint_setup` #3444
- [x] `viewport_litter_paint_setup`

### Supports
- [x] `wooden_a_supports_paint_setup`
- [x] `wooden_b_supports_paint_setup` #4598
- [x] `metal_a_supports_paint_setup`
- [x] `metal_b_supports_paint_setup` #4602
- [x] `path_a_supports_paint_setup` #4590
- [x] `path_b_supports_paint_setup` #4600

### Map Elements
- [x] `viewport_surface_paint_setup` #3358 
- [x] `viewport_path_paint_setup` #3465
- [x] `viewport_track_paint_setup`
- [x] `viewport_scenery_paint_setup` #3639
- [x] `viewport_entrance_paint_setup`
- [x] `viewport_fence_paint_setup` #3498 
- [x] `viewport_banner_paint_setup`
- [x] `viewport_scenery_multiple_paint_setup` #3702

**Comment by IntelOrca** [comment]
OK this page is the fix for #261 and all those peeps that ask for a progress bar.

**Comment by Gymnasiast** [comment]
@IntelOrca @marijnvdwerf Is this indeed an exhaustive list of function left to implement (drawing or otherwise)?

**Comment by IntelOrca** [comment]
@Gymnasiast yep :smiley:

**Comment by janisozaur** [comment]
exciting!

**Comment by duncanspumpkin** [comment]
@marijnvdwerf #3363 is only for the vehicle visual not the track.

**Comment by zsilencer** [comment]
There is also 4 more paint setups for supports

**Comment by Gymnasiast** [comment]
I also did an RCT2_GLOBAL count:
2016-05-12: 5396
2016-05-13: 5387
2016-05-15: 4990
2016-05-16: 4382

**Comment by marijnvdwerf** [comment]
@Gymnasiast Those will probably get higher with each new disassembled ride

**Comment by Gymnasiast** [comment]
@marijnvdwerf Eventually they will reach zero, as it's needed for full implementation.

**Comment by pizza2004** [comment]
You forgot to check off viewport_scenery_multiple_paint_setup

**Comment by Manuel-K** [comment]
@Gymnasiast Are you using `grep RCT_GLOBAL -r . | wc -l`?

Here's a graph:
![2016-05-25](https://cloud.githubusercontent.com/assets/775439/15552588/5fe2e828-22bb-11e6-9fbd-22c8c281e922.png)


Note: Numbers of RCT2_CALLS counts all old drawing function calls as one, because it ignores the array.

**Comment by Gymnasiast** [comment]
@Manuel-K Initially I used `grep -Iri "RCT2_GLOBAL" | wc -l` but now I use `git grep -h -c RCT2_GLOBAL | numsum`.

**Comment by Manuel-K** [comment]
@Gymnasiast Thanks. That's interesting. I've never encountered `numsum`.

**Comment by janisozaur** [comment]
It's important you use `git grep` or similar, as it will only count indexed files, which is why @Gymnasiast's numbers were way off in the beginning.

This still does not provide an exact count, as there are lines with more than one occurrence of `RCT2_GLOBAL` in them, which will only get counted as one. Last time I checked there were around 75 of them, so the number is fairly low and can be skipped.

**Comment by Manuel-K** [comment]
I use a separete checkout to count, so I only have indexed files.

**Comment by Manuel-K** [comment]
@marijnvdwerf I think `wooden_b_supports_paint_setup`, `metal_b_supports_paint_setup`, `path_a_supports_paint_setup` and `path_b_supports_paint_setup` from `src/paint/supports.c` should have checkboxes on the list.

**Comment by marijnvdwerf** [comment]
This can be closed now, right?

**Comment by Margen67** [comment]
What are 55 and 59?

**Comment by IntelOrca** [comment]
@Margen67 I believe they are just place holder IDs for more convenient RCT1 compatibility, more specifically the RCT1 shops which are no longer separate ride types in RCT2.
