### ISSUE TITLE
Rename sub_<hex>() functions

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5525]
```
$ grep -Iri sub_ src/* | wc -l
   19595
```

Current occurrences: 19595

**Comment by IntelOrca** [comment]
Can you get a count for each function?

**Comment by Gymnasiast** [comment]
@IntelOrca There must be a one. But the command I used is mostly to give an indication and roughly keep track of progress anyway.

**Comment by janisozaur** [comment]
```bash
$ grep -ho sub_\[a-fA-F0-9\]\\{5\,7\\} $(git f src) | sort | uniq -c | sort -rn
  14937 sub_98197C
   2534 sub_98196C
   1240 sub_98199C
     77 sub_6C84CE
     54 sub_65E72D
     52 sub_6C9627
     44 sub_693B58
     17 sub_6C683D
     16 sub_6CA2DF
     15 sub_693C9E
     13 sub_6EA934
     13 sub_6D01B3
     11 sub_6E7FF3
      9 sub_6CC3FB
      9 sub_6A759F
      8 sub_6C96C0
      8 sub_693BE5
      8 sub_693BAB
      7 sub_6CB945
      7 sub_6CA162
      7 sub_68A15E
      7 sub_684AC3
      6 sub_88ABA4
      5 sub_98198C
      5 sub_6ED990
      5 sub_6EA8EC
      5 sub_6DFED0
      5 sub_69AF1E
      5 sub_68862C
      4 sub_6EA95D
      4 sub_6D63D4
      4 sub_6C94D8
      4 sub_6A7642
      4 sub_68B3FB
      4 sub_68B089
      4 sub_689174
      3 sub_6EA73F
      3 sub_6E1F34
      3 sub_6DB807
      3 sub_6D7AC0
      3 sub_6CBCE2
      3 sub_6BC2F3
      3 sub_6B7588
      3 sub_6B5952
      3 sub_6AB211
      3 sub_6A3F61
      3 sub_69ED9E
      3 sub_68F8CD
      3 sub_68F41A
      3 sub_68B2B7
      3 sub_685EBC
      3 sub_68371D
      3 sub_679236
      3 sub_679074
      3 sub_679023
      3 sub_666EEF
      2 sub_6DF21B
      2 sub_6DF01A
      2 sub_6DEDE8
      2 sub_6DBF3E
      2 sub_6DB7D6
      2 sub_6D2189
      2 sub_6B2FA9
      2 sub_6A4101
      2 sub_688956
      2 sub_688217
      2 sub_67933B
      2 sub_66F6E3
      1 sub_6EDE88
      1 sub_6A8ACF
      1 sub_68DABD
      1 sub_66E4BA
      1 sub_65E621
```

**Comment by IntelOrca** [comment]
So only 73 renames :p

**Comment by rwjuk** [comment]
Copied from #5532 so we can keep track if that's merged.

* [ ] 14937 `sub_98197C`
* [ ] 2534 `sub_98196C`
* [ ] 1240 `sub_98199C`
* [x] ~~77 `sub_6C84CE`~~ - `window_ride_construction_update_active_elements()`
* [x] ~~54 `sub_65E72D`~~ - `get_num_of_sheltered_eighths()`
* [x] ~~52 `sub_6C9627`~~ - `ride_construction_invalidate_current_track()`
* [x] ~~44 `sub_693B58`~~ - `peep_update_current_action_sprite_type()`
* [ ] 17 `sub_6C683D`
* [ ] 16 `sub_6CA2DF`
* [x] ~~15 `sub_693C9E`~~ - `peep_perform_next_action()`
* [x] ~~13 `sub_6EA934`~~ - `window_fits_within_space()`
* [x] ~~13 `sub_6D01B3`~~ - `place_virtual_track()`
* [x] ~~11 `sub_6E7FF3`~~ - `viewport_redraw_after_shift()`
* [x] ~~9 `sub_6CC3FB`~~ - `ride_initialise_construction_window()`
* [x] ~~9 `sub_6A759F`~~ - `footpath_update_queue_chains()`
* [x] ~~8 `sub_6C96C0`~~ - `ride_construction_remove_ghosts()`
* [x] ~~8 `sub_693BE5`~~ - `peep_switch_to_special_sprite()`
* [x] ~~8 `sub_693BAB`~~ - `peep_switch_to_next_action_sprite_type()`
* [ ] 7 `sub_6CB945`
* [x] ~~7 `sub_6CA162`~~ - `place_provisional_track_piece()`
* [ ] 7 `sub_68A15E`
* [x] ~~7 `sub_684AC3`~~ - `research_reset_current_item()`
* [x] ~~6 `sub_88ABA4`~~ - `paint_crooked_house_structure()`
* [ ] 5 `sub_98198C`
* [x] ~~5 `sub_6ED990`~~ - `set_cursor()`
* [x] ~~5 `sub_6EA8EC`~~
* [x] ~~5 `sub_6DFED0`~~ - `reset_researched_scenery_items()`, see #5536
* [x] ~~5 `sub_69AF1E`~~ - `peep_decide_and_buy_item()`
* [ ] 5 `sub_68862C`
* [x] ~~4 `sub_6EA95D`~~
* [ ] 4 `sub_6D63D4`
* [ ] 4 `sub_6C94D8`
* [x] ~~4 `sub_6A7642`~~ - `footpath_update_queue_entrance_banner()`
* [ ] 4 `sub_68B3FB`
* [ ] 4 `sub_68B089`
* [x] ~~4 `sub_689174`~~ - `viewport_adjust_for_map_height()`
* [x] ~~3 `sub_6EA73F`~~
* [ ] 3 `sub_6E1F34`
* [x] ~~3 `sub_6DB807`~~ - `vehicle_update_reverser_car_bogies()`
* [ ] 3 `sub_6D7AC0`
* [ ] 3 `sub_6CBCE2`
* [ ] 3 `sub_6BC2F3`
* [x] ~~3 `sub_6B7588`~~ - `peep_update_ride_inspected()`
* [ ] 3 `sub_6B5952`
* [ ] 3 `sub_6AB211`
* [ ] 3 `sub_6A3F61`
* [x] ~~3 `sub_69ED9E`~~ - `count_free_misc_sprite_slots()`
* [x] ~~3 `sub_68F8CD`~~ - `peep_decide_whether_to_leave_park()`
* [ ] 3 `sub_68F41A` - see comment below, should probably be folded into `peep_update_all()`
* [ ] 3 `sub_68B2B7`
* [x] ~~3 `sub_685EBC`~~ - `paint_floating_money_effect()`
* [ ] 3 `sub_68371D`
* [ ] 3 `sub_679236`
* [ ] 3 `sub_679074`
* [ ] 3 `sub_679023`
* [x] ~~3 `sub_666EEF`~~ - `place_park_entrance_get_map_position()`
* [ ] 2 `sub_6DF21B`
* [ ] 2 `sub_6DF01A`
* [x] ~~2 `sub_6DEDE8`~~ - `vehicle_update_handle_scenery_door()`
* [ ] 2 `sub_6DBF3E`
* [x] ~~2 `sub_6DB7D6`~~ - `vehicle_reverse_reverser_car()`
* [x] ~~2 `sub_6D2189`~~ - `track_design_place_preview()`
* [x] ~~2 `sub_6B2FA9`~~ - `close_ride_window_for_construction()`
* [ ] 2 `sub_6A4101`
* [x] ~~2 `sub_688956`~~ - `call_event_unknown_14_on_all_windows()`
* [ ] 2 `sub_688217` - doesn't appear to exist, used in lightfx.c L294
* [ ] 2 `sub_67933B`
* [x] ~~2 `sub_66F6E3`~~ - elided
* [x] ~~1 `sub_6EDE88`~~ - declared but never defined
* [x] ~~1 `sub_6A8ACF`~~ - comment only
* [x] ~~1 `sub_68DABD`~~ - comment only 
* [x] ~~1 `sub_66E4BA`~~ - comment only
* [x] ~~1 `sub_65E621`~~ - comment only

**Comment by Gymnasiast** [comment]
Quoting @ZehMatt :

> I believe byte_9D8150 is set when it wants the preview only. We could call this something like 'previewMode'
