### ISSUE TITLE
Refactor game commands to game actions.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#6327]
## Rides/Construction
- [x] GAME_COMMAND_SET_RIDE_APPEARANCE #8676
- [x] GAME_COMMAND_PLACE_TRACK #8694 
- [x] GAME_COMMAND_REMOVE_TRACK #8730 
- [x] GAME_COMMAND_CREATE_RIDE #5053
- [x] GAME_COMMAND_DEMOLISH_RIDE #5053
- [x] GAME_COMMAND_SET_RIDE_STATUS #5053
- [x] GAME_COMMAND_SET_RIDE_VEHICLES #8738
- [x] GAME_COMMAND_SET_RIDE_NAME #5053
- [x] GAME_COMMAND_SET_RIDE_SETTING #8740
- [x] GAME_COMMAND_PLACE_RIDE_ENTRANCE_OR_EXIT #8796
- [x] GAME_COMMAND_REMOVE_RIDE_ENTRANCE_OR_EXIT #8762
- [x] GAME_COMMAND_SET_RIDE_PRICE #8693
- [x] GAME_COMMAND_SET_BRAKES_SPEED #8852
- [x] GAME_COMMAND_SET_MAZE_TRACK #6966
- [ ] GAME_COMMAND_PLACE_TRACK_DESIGN #10189
- [x] GAME_COMMAND_PLACE_MAZE_DESIGN #10119

## Footpath
- [x] GAME_COMMAND_PLACE_PATH #8807
- [x] GAME_COMMAND_PLACE_PATH_FROM_TRACK #8830
- [x] GAME_COMMAND_REMOVE_PATH #7867

## Park
- [x] GAME_COMMAND_SET_PARK_ENTRANCE_FEE #5053
- [x] GAME_COMMAND_RAISE_LAND #8826
- [x] GAME_COMMAND_LOWER_LAND #8826
- [x] GAME_COMMAND_EDIT_LAND_SMOOTH #8902
- [x] GAME_COMMAND_RAISE_WATER #8826
- [x] GAME_COMMAND_LOWER_WATER #8826
- [x] GAME_COMMAND_SET_PARK_NAME #7343
- [x] GAME_COMMAND_SET_PARK_OPEN #8881
- [x] GAME_COMMAND_BUY_LAND_RIGHTS #8914
- [x] GAME_COMMAND_PLACE_PARK_ENTRANCE #5053
- [x] GAME_COMMAND_REMOVE_PARK_ENTRANCE #8935
- [x] GAME_COMMAND_SET_LAND_HEIGHT #8689
- [x] GAME_COMMAND_SET_WATER_HEIGHT #8799
- [x] GAME_COMMAND_SET_LAND_OWNERSHIP #8914
- [x] GAME_COMMAND_MODIFY_TILE #9264
- [x] GAME_COMMAND_CHANGE_SURFACE_STYLE #8897

## Staff 
- [x] GAME_COMMAND_SET_STAFF_NAME #5053 / #6347
- [x] GAME_COMMAND_HIRE_NEW_STAFF_MEMBER #8849
- [x] GAME_COMMAND_SET_STAFF_PATROL #8898
- [x] GAME_COMMAND_FIRE_STAFF_MEMBER #8898
- [x] GAME_COMMAND_SET_STAFF_ORDER #8668
- [x] GAME_COMMAND_SET_CURRENT_LOAN #7286
- [x] GAME_COMMAND_SET_STAFF_COLOUR #7286
- [x] GAME_COMMAND_PICKUP_STAFF #9392

## Guests
- [x] GAME_COMMAND_SET_GUEST_NAME #5053 / #6347
- [x] GAME_COMMAND_PICKUP_GUEST #9392

## Scenario
- [x] GAME_COMMAND_SET_RESEARCH_FUNDING #7286
- [x] GAME_COMMAND_START_MARKETING_CAMPAIGN #7286
- [x] GAME_COMMAND_EDIT_SCENARIO_OPTIONS #9259 

## Game
- [x] GAME_COMMAND_LOAD_OR_QUIT #8737
- [x] GAME_COMMAND_TOGGLE_PAUSE #8690 
- [x] GAME_COMMAND_BALLOON_PRESS #9250
- [x] GAME_COMMAND_SET_PLAYER_GROUP #9072
- [x] GAME_COMMAND_MODIFY_GROUPS #9244
- [x] GAME_COMMAND_KICK_PLAYER #9244
- [x] GAME_COMMAND_CHEAT #8990

## Scenery
- [x] GAME_COMMAND_PLACE_WALL #8966
- [x] GAME_COMMAND_REMOVE_WALL #6807
- [x] GAME_COMMAND_PLACE_LARGE_SCENERY #9055
- [x] GAME_COMMAND_REMOVE_LARGE_SCENERY #8525
- [x] GAME_COMMAND_SET_SCENERY_COLOUR #9064
- [x] GAME_COMMAND_SET_WALL_COLOUR #9064
- [x] GAME_COMMAND_SET_LARGE_SCENERY_COLOUR #9064
- [x] GAME_COMMAND_SET_BANNER_COLOUR #9064
- [x] GAME_COMMAND_SET_BANNER_STYLE #9064
- [x] GAME_COMMAND_SET_BANNER_NAME #7343
- [x] GAME_COMMAND_REMOVE_BANNER #9059
- [x] GAME_COMMAND_CLEAR_SCENERY #7381 / #8525
- [x] GAME_COMMAND_SET_SIGN_NAME #7343
- [x] GAME_COMMAND_SET_SIGN_STYLE #8666
- [x] GAME_COMMAND_REMOVE_SCENERY #8525
- [x] GAME_COMMAND_PLACE_SCENERY #8773
- [x] GAME_COMMAND_PLACE_BANNER #9059

**Comment by ZehMatt** [comment]
For myself
```
 
R = Referenced by other game command.
 
GAME_COMMAND_SET_RIDE_APPEARANCE -> game_command_set_ride_appearance
GAME_COMMAND_SET_LAND_HEIGHT*R -> game_command_set_land_height -> map_set_land_height
GAME_COMMAND_TOGGLE_PAUSE -> game_pause_toggle
GAME_COMMAND_PLACE_TRACK*R -> game_command_place_track -> track_place -> track_add_station_element*R
GAME_COMMAND_REMOVE_TRACK*R -> game_command_remove_track -> track_remove -> track_remove_station_element*R
GAME_COMMAND_LOAD_OR_QUIT -> game_load_or_quit
GAME_COMMAND_CREATE_RIDE // GA 
GAME_COMMAND_DEMOLISH_RIDE // GA
GAME_COMMAND_SET_RIDE_STATUS // GA 
GAME_COMMAND_SET_RIDE_VEHICLES*R -> game_command_set_ride_vehicles -> ride_set_vehicles
GAME_COMMAND_SET_RIDE_NAME // GA
GAME_COMMAND_SET_RIDE_SETTING*R -> game_command_set_ride_setting -> ride_set_setting
GAME_COMMAND_PLACE_RIDE_ENTRANCE_OR_EXIT*R -> game_command_place_ride_entrance_or_exit -> RideEntranceExitPlace -> 
	GAME_COMMAND_REMOVE_RIDE_ENTRANCE_OR_EXIT
GAME_COMMAND_REMOVE_RIDE_ENTRANCE_OR_EXIT*R -> game_command_remove_ride_entrance_or_exit -> RideEntranceExitRemove
GAME_COMMAND_REMOVE_SCENERY*R -> game_command_remove_scenery -> SmallSceneryRemove
GAME_COMMAND_PLACE_SCENERY*R -> game_command_place_scenery -> SmallSceneryPlace
GAME_COMMAND_SET_WATER_HEIGHT*R -> game_command_set_water_height
GAME_COMMAND_PLACE_PATH -> game_command_place_footpath -> footpath_place_real -> footpath_provisional_remove -> footpath_remove -> 
	GAME_COMMAND_REMOVE_PATH
GAME_COMMAND_PLACE_PATH_FROM_TRACK*R -> game_command_place_footpath_from_track -> footpath_place_from_track				   
GAME_COMMAND_REMOVE_PATH*R -> game_command_remove_footpath -> footpath_remove_real
GAME_COMMAND_CHANGE_SURFACE_STYLE -> game_command_change_surface_style -> map_change_surface_style
GAME_COMMAND_SET_RIDE_PRICE -> game_command_set_ride_price
GAME_COMMAND_SET_GUEST_NAME // GA
GAME_COMMAND_SET_STAFF_NAME // GA
GAME_COMMAND_RAISE_LAND*R -> game_command_raise_land -> raise_land
GAME_COMMAND_LOWER_LAND*R -> game_command_lower_land -> lower_land
GAME_COMMAND_EDIT_LAND_SMOOTH -> game_command_smooth_land -> smooth_land -> 
	GAME_COMMAND_RAISE_LAND,
	GAME_COMMAND_LOWER_LAND,
	GAME_COMMAND_SET_LAND_HEIGHT
GAME_COMMAND_RAISE_WATER -> game_command_raise_water -> raise_water -> 
	GAME_COMMAND_SET_WATER_HEIGHT
GAME_COMMAND_LOWER_WATER -> game_command_lower_water -> lower_water ->
	GAME_COMMAND_SET_WATER_HEIGHT
GAME_COMMAND_SET_BRAKES_SPEED -> game_command_set_brakes_speed
GAME_COMMAND_HIRE_NEW_STAFF_MEMBER -> game_command_hire_new_staff_member -> staff_hire_new_staff_member
GAME_COMMAND_SET_STAFF_PATROL -> game_command_set_staff_patrol
GAME_COMMAND_FIRE_STAFF_MEMBER -> game_command_fire_staff_member
GAME_COMMAND_SET_STAFF_ORDER -> game_command_set_staff_order
GAME_COMMAND_SET_PARK_NAME -> game_command_set_park_name
GAME_COMMAND_SET_PARK_OPEN -> game_command_set_park_open
GAME_COMMAND_BUY_LAND_RIGHTS -> game_command_buy_land_rights -> map_buy_land_rights
GAME_COMMAND_PLACE_PARK_ENTRANCE // GA
GAME_COMMAND_REMOVE_PARK_ENTRANCE -> game_command_remove_park_entrance -> ParkEntranceRemove
GAME_COMMAND_SET_MAZE_TRACK -> game_command_set_maze_track -> set_maze_track
GAME_COMMAND_SET_PARK_ENTRANCE_FEE // GA 
GAME_COMMAND_SET_STAFF_COLOUR -> game_command_update_staff_colour
GAME_COMMAND_PLACE_WALL*R -> game_command_place_wall -> WallPlace
GAME_COMMAND_REMOVE_WALL*R -> game_command_remove_wall -> WallRemove
GAME_COMMAND_PLACE_LARGE_SCENERY*R -> game_command_place_large_scenery
GAME_COMMAND_REMOVE_LARGE_SCENERY*R -> game_command_remove_large_scenery
GAME_COMMAND_SET_CURRENT_LOAN -> game_command_set_current_loan
GAME_COMMAND_SET_RESEARCH_FUNDING -> game_command_set_research_funding
GAME_COMMAND_PLACE_TRACK_DESIGN -> game_command_place_track_design -> place_track_design -> 
	ride_create_command(GA), 
	ride_demolish(GA), 
	GAME_COMMAND_PLACE_MAZE_DESIGN, 
	GAME_COMMAND_PLACE_RIDE_ENTRANCE_OR_EXIT,
	GAME_COMMAND_SET_RIDE_VEHICLES,
	GAME_COMMAND_SET_RIDE_SETTING,
	GAME_COMMAND_REMOVE_TRACK,
	GAME_COMMAND_PLACE_TRACK,
	GAME_COMMAND_REMOVE_SCENERY,
	GAME_COMMAND_REMOVE_LARGE_SCENERY,
	GAME_COMMAND_REMOVE_WALL,
	GAME_COMMAND_PLACE_SCENERY,
	GAME_COMMAND_PLACE_LARGE_SCENERY,
	GAME_COMMAND_PLACE_WALL,
	GAME_COMMAND_PLACE_PATH_FROM_TRACK,
GAME_COMMAND_START_MARKETING_CAMPAIGN -> game_command_start_campaign
GAME_COMMAND_PLACE_MAZE_DESIGN -> game_command_place_maze_design -> place_maze_design
GAME_COMMAND_PLACE_BANNER -> game_command_place_banner -> BannerPlace
GAME_COMMAND_REMOVE_BANNER -> game_command_remove_banner -> BannerRemove
GAME_COMMAND_SET_SCENERY_COLOUR -> game_command_set_scenery_colour -> SmallScenerySetColour
GAME_COMMAND_SET_WALL_COLOUR -> game_command_set_wall_colour -> WallSetColour
GAME_COMMAND_SET_LARGE_SCENERY_COLOUR -> game_command_set_large_scenery_colour
GAME_COMMAND_SET_BANNER_COLOUR -> game_command_set_banner_colour -> BannerSetColour
GAME_COMMAND_SET_LAND_OWNERSHIP -> game_command_set_land_ownership -> map_set_land_ownership -> map_buy_land_rights
GAME_COMMAND_CLEAR_SCENERY -> game_command_clear_scenery -> map_clear_scenery -> map_clear_scenery_from_tile -> 
	GAME_COMMAND_REMOVE_PATH
	GAME_COMMAND_REMOVE_SCENERY
	GAME_COMMAND_REMOVE_WALL
	GAME_COMMAND_REMOVE_LARGE_SCENERY
GAME_COMMAND_SET_BANNER_NAME -> game_command_set_banner_name -> BannerSetName																 
GAME_COMMAND_SET_SIGN_NAME -> game_command_set_sign_name
GAME_COMMAND_SET_BANNER_STYLE -> game_command_set_banner_style -> BannerSetStyle
GAME_COMMAND_SET_SIGN_STYLE -> game_command_set_sign_style
GAME_COMMAND_SET_PLAYER_GROUP -> game_command_set_player_group
GAME_COMMAND_MODIFY_GROUPS -> game_command_modify_groups
GAME_COMMAND_KICK_PLAYER -> game_command_kick_player
GAME_COMMAND_CHEAT -> game_command_cheat
GAME_COMMAND_PICKUP_GUEST -> game_command_pickup_guest -> peep_pickup_command
GAME_COMMAND_PICKUP_STAFF -> game_command_pickup_staff -> peep_pickup_command
GAME_COMMAND_BALLOON_PRESS -> game_command_balloon_press
GAME_COMMAND_MODIFY_TILE -> game_command_modify_tile
GAME_COMMAND_EDIT_SCENARIO_OPTIONS -> game_command_edit_scenario_options
```

**Comment by duncanspumpkin** [comment]
Checklist:

- [ ] Port game command to game action. Create new file, xcodefix.
- [ ] Register game action. `src/openrct2/actions/GameActionRegistration.cpp`
- [ ] Port all call references.
- [ ] Swap old game command with nullptr in table. `src/openrct2/game.cpp`
- [ ] Mark old game command with `// GA` in table. `src/openrct2/game.h`
- [ ] Singleplayer tests.
- [ ] Multiplayer tests.

**Comment by Gymnasiast** [comment]
Stuff that doesn't have a game command/game action, but needs one:
- [x] Setting colour scheme of track parts https://github.com/OpenRCT2/OpenRCT2/pull/8420
- [ ] Setting date: https://github.com/OpenRCT2/OpenRCT2/issues/8649

(Feel free to edit this post to list more)

**Comment by janisozaur** [comment]
This seems done. @ZehMatt can you confirm and close?

**Comment by duncanspumpkin** [comment]
One left

**Comment by tupaschoal** [comment]
Hooray!
